In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import average_precision_score
from sklearn.metrics import precision_recall_curve
from sklearn.utils import resample
from imblearn.over_sampling import SMOTE

In [3]:
df = pd.read_csv("train.csv") 

In [7]:
df.target.value_counts()

0    179902
1     20098
Name: target, dtype: int64

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn import metrics as m
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.model_selection import ShuffleSplit
from sklearn.metrics import roc_auc_score

In [5]:
X = df.drop(["ID_code","target"], axis = 1)
y = df.target

In [10]:
X = df.drop(["ID_code","target"], axis = 1)
y = df.target

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 1, stratify=y)
y_train.value_counts()
ad = GradientBoostingClassifier()
ad.fit(X_train, y_train)

y_pred = ad.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)

ac = accuracy_score(y_test, y_pred)
print(ac)

rs = recall_score(y_test, y_pred)
print(rs)

ras = roc_auc_score(y_test, y_pred)
print(ras)


[[44949    26]
 [ 4869   156]]
0.9021
0.031044776119402984
0.5152333385877726


In [11]:
y_train.value_counts()

0    134927
1     15073
Name: target, dtype: int64

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 1, stratify=y)
smt = SMOTE()
X_train, y_train = smt.fit_sample(X_train, y_train)

In [13]:
np.bincount(y_train)

array([134927, 134927], dtype=int64)

In [14]:
ad = GradientBoostingClassifier()
ad.fit(X_train, y_train)

y_pred = ad.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)

ac = accuracy_score(y_test, y_pred)
print(ac)

rs = recall_score(y_test, y_pred)
print(rs)

ras = roc_auc_score(y_test, y_pred)
print(ras)

[[38280  6695]
 [ 3242  1783]]
0.80126
0.3548258706467662
0.6029826963017043


In [6]:
from imblearn.under_sampling import NearMiss
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 0, stratify=y)

nr = NearMiss()
X_train, y_train = nr.fit_sample(X_train, y_train)
np.bincount(y_train)


array([15074, 15074], dtype=int64)

In [20]:
ad = GradientBoostingClassifier()
ad.fit(X_train, y_train)

y_pred = ad.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)

ac = accuracy_score(y_test, y_pred)
print(ac)

rs = recall_score(y_test, y_pred)
print(rs)

ras = roc_auc_score(y_test, y_pred)
print(ras)

[[30497 14479]
 [ 1124  3900]]
0.68794
0.7762738853503185
0.7271733176306912


In [ ]:
C = 1.0 

In [2]:
# from sklearn import svm 
# # SVC with linear kernel

# svc = svm.SVC(kernel='linear', C=C).fit(X_train, y_train)
# y_pred = svc.predict(X_test)

# cm = confusion_matrix(y_test, y_pred)
# print(cm)

# ac = accuracy_score(y_test, y_pred)
# print(ac)

# rs = recall_score(y_test, y_pred)
# print(rs)

# ras = roc_auc_score(y_test, y_pred)
# print(ras)


In [1]:
# poly_svc = svm.SVC(kernel='poly', degree=3, C=C).fit(X_train, y_train)
# y_pred = poly_svc.predict(X_test)

# cm = confusion_matrix(y_test, y_pred)
# print(cm)

# ac = accuracy_score(y_test, y_pred)
# print(ac)

# rs = recall_score(y_test, y_pred)
# print(rs)

# ras = roc_auc_score(y_test, y_pred)
# print(ras)

In [9]:
from sklearn.linear_model import LogisticRegression
lg = LogisticRegression()
lg.fit(X_train, y_train)

y_pred = lg.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)

ac = accuracy_score(y_test, y_pred)
print(ac)

rs = recall_score(y_test, y_pred)
print(rs)

ras = roc_auc_score(y_test, y_pred)
print(ras)

C:\Users\Ayushi.Goel\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


[[35678  9298]
 [ 1222  3802]]
0.7896
0.7567675159235668
0.7750175181894605


In [7]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
# Fit only to the training data
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [8]:
# Now apply the transformations to the data:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
from sklearn.neural_network import MLPClassifier

In [13]:
mlp = MLPClassifier(hidden_layer_sizes=(200,200,200))

In [14]:
mlp.fit(X_train,y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(200, 200, 200), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [15]:
predictions = mlp.predict(X_test)

In [16]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,predictions))

[[30487 14489]
 [ 1214  3810]]


In [17]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

ac = accuracy_score(y_test, y_pred)
print(ac)

rs = recall_score(y_test, y_pred)
print(rs)

ras = roc_auc_score(y_test, y_pred)
print(ras)

[[35678  9298]
 [ 1222  3802]]
0.7896
0.7567675159235668
0.7750175181894605


In [10]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
# Feature extraction
model = LogisticRegression(solver='lbfgs')
rfe = RFE(model, 10)
fit = rfe.fit(X_train, y_train)
print("Num Features: %s" % (fit.n_features_))
print("Selected Features: %s" % (fit.support_))
print("Feature Ranking: %s" % (fit.ranking_))

Num Features: 10
Selected Features: [False False False False False False  True False False False False False
  True False False False False False False False False False  True False
 False False  True False False False False False False False False False
 False False False False False False False False  True False False False
 False False False False False  True False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False  True False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False  True False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False  True False False False False
 False False False False False False False False False False False False
 False False Fa